replicaCount: 1

images:
  nginx:
    repository: nginx
    tag: latest
    pullPolicy: IfNotPresent
  multitool:
    repository: wbitt/network-multitool
    tag: latest
    pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: false
  host: myapp.example.com
  tls:
    enabled: false
    secretName: tls-secret

configmap:
  enabled: true
  title: "Страница из Helm-чарта"
  heading: "Привет от Helm!"
  message: "Это приложение развёрнуто с помощью Helm"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi