{
 "title": "CPU",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(node_load1, \"instance\", \"LA 1m\", \"instance\", \".*\")",
     "legendFormat": "{{LA 1m}}"
    },
    {
     "expr": "label_replace(node_load5, \"instance\", \"LA 5m\", \"instance\", \".*\")",
     "legendFormat": "{{LA 5m}}"
    },
    {
     "expr": "label_replace(node_load15,\"instance\",\"LA 15m\",\"instance\",\".*\")",
     "legendFormat": "{{LA m15}}"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes / 1073741824",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Disk Space",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{mountpoint=\"/\"} / 1000000000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}