apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-app-service
  labels:
    app: web-app
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: web-app
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}