apiVersion: v1
kind: PersistentVolume
metadata:
  name: task3-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data-task3
  storageClassName: task3-sc