apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: task3-sc  
provisioner: kubernetes.io/no-provisioner  
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task3-pvc  
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  
  storageClassName: task3-sc  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange-sc
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: data-exchange-sc  
  template:
    metadata:
      labels:
        app: data-exchange-sc  
    spec:
      containers:
      - name: writer  
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["while true; do echo $(date) > /shared/data.txt; sleep 5; done"]
        volumeMounts:
        - name: task3-storage  
          mountPath: /shared
      - name: reader  
        image: wbitt/network-multitool
        command: ["/bin/sh", "-c"]
        args: ["tail -f /shared/data.txt"]
        volumeMounts:
        - name: task3-storage  
          mountPath: /shared
      volumes:
      - name: task3-storage  
        persistentVolumeClaim:
          claimName: task3-pvc  